# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0005_auto_20180607_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_socio',
            name='isPay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb_socio',
            name='montoPagado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tb_socio',
            name='statusPago',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Parcialmente Pagado', 'Parcialmente Pagado'), ('Pendiente por Pagar', 'Pendiente por Pagar')], default='Pendiente por Pagar', max_length=255),
        ),
    ]
