# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-29 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0006_auto_20190122_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_socio',
            name='statusPago',
        ),
    ]
