# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-15 13:49
from __future__ import unicode_literals

import apps.Configuracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0007_remove_tb_socio_statuspago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_socio',
            name='descuento',
            field=models.FloatField(default='0000', null=True, verbose_name=apps.Configuracion.models.tb_porcentaje),
        ),
    ]
