# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0008_tb_socio_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_socio',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
