# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0009_auto_20190215_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_socio',
            name='TarifaconDescuento',
            field=models.FloatField(default='0000', null=True),
        ),
    ]
