# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-20 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0013_auto_20190220_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_socio',
            name='TarifaconDescuento',
            field=models.FloatField(default='0000', null=True),
        ),
    ]
