# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-20 23:02
from __future__ import unicode_literals

import apps.Configuracion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0014_auto_20190220_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_socio',
            name='TarifaconDescuento',
            field=models.FloatField(default='0000', null=True, verbose_name=apps.Configuracion.models.tb_porcentaje),
        ),
    ]
