# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0019_tb_plan_diario'),
        ('Socios', '0015_auto_20190220_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_socio',
            name='TarifaDiaria',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_plan_diario'),
        ),
    ]
