# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0017_auto_20190306_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_socio',
            name='AcceptTerms',
            field=models.BooleanField(default=False),
        ),
    ]
