# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCancha', models.CharField(default='Sin Datos', max_length=300, null=True)),
                ('precioHora', models.FloatField(default='0', null=True)),
                ('description', models.TextField(default='Sin Datos', null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='cancha/img/')),
                ('dateCreate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'canchas',
                'managed': True,
            },
        ),
    ]
