# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Canchas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(default='', max_length=30)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('telefono', models.CharField(default='', max_length=30)),
                ('statusTurn', models.CharField(choices=[('Confirmada', 'Confirmada'), ('En Espera', 'En Espera'), ('No Aprobada', 'En Espera')], default='En Espera', max_length=255)),
                ('dateTurn', models.DateField(blank=True, default='')),
                ('montoAPagar', models.IntegerField(blank=True, default=0)),
                ('montoPagado', models.IntegerField(blank=True, default=0, null=True)),
                ('isPay', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='Sin Descripcion', max_length=3000000)),
                ('TipoReservas', models.CharField(default='Reserva Web', max_length=30, null=True)),
                ('observaciones', models.TextField(default='Sin Obsevaciones', max_length=3000)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('cancha', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Canchas.Cancha')),
            ],
            options={
                'db_table': 'ReservaCancha',
                'managed': True,
            },
        ),
    ]
