# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0007_tb_turn_sesion'),
        ('Canchas', '0002_reservacancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacancha',
            name='turn',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_turn_sesion'),
        ),
        migrations.AlterField(
            model_name='reservacancha',
            name='statusTurn',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('En Espera', 'En Espera'), ('No Aprobada', 'No Aprobada')], default='En Espera', max_length=255),
        ),
    ]
