# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canchas', '0003_auto_20181205_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacancha',
            name='statusPago',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Parcialmente Pagado', 'Parcialmente Pagado'), ('Pendiente por Pagar', 'Pendiente por Pagar')], default='Pendiente por Pagar', max_length=255),
        ),
    ]
