# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-20 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0011_auto_20180814_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_ingresos',
            name='status',
            field=models.CharField(choices=[('IsPay', 'IsPay'), ('NoPay', 'NoPay')], default='NoPay', max_length=30),
        ),
    ]
