# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-20 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0012_tb_ingresos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_ingresos',
            name='status',
        ),
    ]
