# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-06 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0013_auto_20190128_2218'),
        ('Caja', '0013_remove_tb_ingresos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_ingresos',
            name='tipoPago',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_formasDePago'),
        ),
    ]
