# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-12 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0015_auto_20190212_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_egreso',
            name='tipoPago',
        ),
    ]
