# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-18 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0009_auto_20181217_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_tipoHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametipoHorario', models.CharField(default='', max_length=30, unique=True)),
                ('HoraTurn', models.TimeField(default='')),
                ('HoraTurnEnd', models.TimeField(default='')),
                ('dateCreate', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
