# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-29 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0011_auto_20190117_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_plan',
            name='precioPlan',
            field=models.FloatField(default='000000', max_length=30, null=True),
        ),
    ]
