# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0012_auto_20190128_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_plan',
            name='precioPlan',
            field=models.CharField(default='000000', max_length=30, null=True),
        ),
    ]
