# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-13 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0013_auto_20190128_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_porcentaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(default='0', null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(default='Sin Descripcion', max_length=3000, null=True)),
                ('titulo', models.CharField(default='Sin titulo', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'porcentaje',
            },
        ),
    ]
