# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-15 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0014_tb_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_porcentaje',
            name='titulo',
        ),
    ]
