# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0016_auto_20190215_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_porcentaje',
            name='porcentaje',
            field=models.FloatField(default='0', null=True),
        ),
    ]
