# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-28 00:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0017_auto_20190215_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_mailsAdministrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreate', models.DateField(auto_now=True)),
                ('mail', models.EmailField(default='sin@definir.com', max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mailadmin',
                'managed': True,
            },
        ),
    ]
