# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-14 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0019_tb_plan_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_termino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTerminos', models.CharField(default='', max_length=30, unique=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(default='Sin Descripcion', max_length=3000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'Terminos',
            },
        ),
    ]
